// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as BlogBlogRoute from "@/app/(blog)/blog/page.info";
import * as BlogBlogSlugRoute from "@/app/(blog)/blog/[slug]/page.info";
import * as BlogBlogSlugCommentsRoute from "@/app/(blog)/blog/[slug]/@comments/page.info";
import * as BlogBlogSlugOthersRoute from "@/app/(blog)/blog/[slug]/@others/page.info";
import * as HomeRoute from "@/app/(home)/page.info";
import * as ApiAuthNextauthRoute from "@/app/api/auth/[...nextauth]/route.info";
import * as ApiGenOgImagesSlugRoute from "@/app/api/gen-og-images/[slug]/route.info";

export const BlogBlog = makeRoute(
  "/(blog)/blog",
  {
    ...defaultInfo,
    ...BlogBlogRoute.Route
  }
);
export const BlogBlogSlug = makeRoute(
  "/(blog)/blog/[slug]",
  {
    ...defaultInfo,
    ...BlogBlogSlugRoute.Route
  }
);
export const BlogBlogSlugComments = makeRoute(
  "/(blog)/blog/[slug]/@comments",
  {
    ...defaultInfo,
    ...BlogBlogSlugCommentsRoute.Route
  }
);
export const BlogBlogSlugOthers = makeRoute(
  "/(blog)/blog/[slug]/@others",
  {
    ...defaultInfo,
    ...BlogBlogSlugOthersRoute.Route
  }
);
export const Home = makeRoute(
  "/(home)",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const ApiAuthNextauth = makeRoute(
  "/api/auth/[...nextauth]",
  {
    ...defaultInfo,
    ...ApiAuthNextauthRoute.Route
  }
);

export const getApiGenOgImagesSlug = makeGetRoute(
  "/api/gen-og-images/[slug]",
  {
    ...defaultInfo,
    ...ApiGenOgImagesSlugRoute.Route
  },
  ApiGenOgImagesSlugRoute.GET
);
